### ISSUE TITLE
Build fails for iOS: main.jsbundle does not exist

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-CoachApp#104]
The issue appears during buildtime on XCode:
...Build/Products/Release-iphoneos/America Scores Attendance.app/main.jsbundle does not exist. This must be a bug with'
Searching shows this being a react-native issue that Facebook says is linked to an XCode build update:
https://github.com/facebook/react-native/issues/29356

**Comment by popking5466** [comment]
### This operation worked for me and saved my week :) 

Add this to the package.json - scripts

`"bundle:ios": "node ./node_modules/react-native/local-cli/cli.js bundle --platform ios --entry-file index.js --bundle-output ios/**yourAppName**/main.jsbundle --dev=false --verbose"`

Now you can run the command to generate main.jsbundle:

`npx yarn bundle:ios`

Open the Xcode -> Select project target -> add `main.jsbundle` to `Copy Bundle Resource` in `Build Phases`

`Archive` again.

[https://ananda-gopal.medium.com/react-native-main-jsbundle-does-not-exist-5e9c3527554f](url)
