### ISSUE TITLE
[bug] Log in without phone number authentication sometimes makes app crash

### ISSUE THREAD

**Issue by lautirozen** [AmericaSCORESBayArea/AmericaScores-CoachApp#159]
To reproduce:

- login as a coach with Gmail or Apple ID.
- logout
- login again with Gmail or Apple ID.
At this point, the app may crash.

**Comment by CritiqalPete** [comment]
on iOS login with AppleID works but first attempt (after updating to new release) appeared to fail (Account not found) @lautirozen different or related bug?
