### ISSUE TITLE
Coach can modify session properties and schedule

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-CoachApp#18]
The coach may need to create a schedule for a newly formed team, at the beginning of a new season, or in the middle to reflect a change in meetings. 
UX Example using Calendar Widget to Modify a Session Schedule:
1. Coach selects Change Schedule from the Sessions View
2. The Calendar Widget or List View provides the session date and type
3. Coach can tap the date to cycle through the session types, or alternate add/remove the session. An extra tap continues the cycle
4. The CONFIRM button includes a summary of the changes:
[n Added      m Removed     o Changed]

**MVP**
1. Coach selects a session by date
2. Coach selects Modify Session option from the drop-down menu (this is used rarely)
3. Session Properties are displayed for edit:
- Delete Session
- Change Day (select a different day of the week)
- Change Start/Finish Date (limited to Season)
- Change Session Type (picklist)

Validation:
If a Session already has attendance recorded, then it can't be deleted. "All attendance must be removed from this session before it can be deleted."

Additional documentation:
Technical details of this feature can be found in https://github.com/AmericaSCORESBayArea/scoreslabs/blob/main/Changes%20to%20Sessions%20and%20Team%20Seasons%20on-the-fly.md

**Comment by CritiqalPete** [comment]
@Ignacioals I believe we need to push this out of this UAT milestone. Am I correct?

**Comment by Ignacioals** [comment]
@CritiqalPete this is a big feature, we might need to evaluate API dependencies for this, it would be better to push it.

**Comment by CritiqalPete** [comment]
Hi @Ignacioals and @archana-llamas this high-value ticket was assigned to @cyanzon-mulesoft but I'm not sure he's been able to look at it for weeks. Now it's becoming a priority and I suspect we'll need to test and refine it over a few weeks as more coaches start using the app. Can we please work out a way to get this started, call out any API dependencies, and an MVP implementation?
