### ISSUE TITLE
(critical) Coach can set Session Type for anonymous program sessions

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-CoachApp#332]
The data team considers only the Session Type field for participation analysis and Program has agreed that sessions for anonymous programs like Scores Go will benefit from this level of detail.
The UX should provide for adding and modifying sessions just like with regular attendance team types.

**Comment by lautirozen** [comment]
![image](https://user-images.githubusercontent.com/62625969/204035555-fc56808c-e7b2-4faa-9597-ba43ae2a69a2.png)
