### ISSUE TITLE
Coach can select a preference of Today or This Week when viewing sessions

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-CoachApp#336]
Coaches often find more than one day at a time too much to view but the work of changing the calendar too time consuming.
Proposed UI Feature:
_A Toggle [Today|This Week] is available where the calendar is displayed_
1. Default view may remain Current Week
2. Coach may open the calendar to tap the Toggle. The alternate is highlighted and the view is updated on the calendar and underlying Session/Team view.
3. The app remembers this choice as a default-preference
4. Coach and switch that preference at any time
5. Changing the calendar date range overrides this preference only for the current session. Tapping the toggle again will override that manual calendar scope again.

Requested by: Coach Kevin (Scores Staff Manager)

**Comment by lautirozen** [comment]
Message: Select how many days to see in your session list by default.
Options:
- Today
- Week
- Month
