### ISSUE TITLE
Verify npm 10.2+

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-CoachApp#435]
a new release 10.2.5 is out.
let's verify we can build and run and that dependencies are updated properly,

**Comment by nglover53** [comment]
@CritiqalPete  

To verify successful build with older version (9.6.3): 

1. Try to run build with : npm react-native start   
2. update using: npm update
3. Run npx react-native start   once again to make sure it takes us to running build 

Purpose: If this can be used as universal run command.

**Comment by nglover53** [comment]
@CritiqalPete was able to run: react-native start in the pre-update npm version. But full build was not deployed until keypress 'a'
