### ISSUE TITLE
Update UIKitten to Latest

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-CoachApp#437]
@lautirozen please update this with a version target and where a dev could look for dependencies

**Comment by nglover53** [comment]
Planning to work on this issue this week. Will drop in on Wednesday for questions about blockers or technical surprises/ build errors. 

Proceeding by: Creating a branch for this issue, updating correct pods, and running a build to make sure all functionality is preserved, then will review with other engineers.

**Comment by nglover53** [comment]
Process for Updating Library

- Create a branch for updating the library and create a cloned repo locally 
- UIKitten library is 5.3.1
- Checked through UIKitten Github (Latest release updated April 2023)

https://github.com/akveo/react-native-ui-kitten/releases/tag/v5.3.1

- Kit is up to date

**Comment by nglover53** [comment]
Closed, no change needed
