### ISSUE TITLE
Views of Sessions should be titled as Sessions. Activity-type is always a property or description of a Session.

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-CoachApp#44]
The UI needs to clearly distinguish what part(s) of the hierarchy is in view. 
Also the terminology in the Nav needs to match the view title.
In this case, the title of a list of Sessions needs to be "Sessions." (presently it's "Team Activities")

**Comment by Ignacioals** [comment]
@CritiqalPete The screen for "Team Activities" and "Sessions" are different, although they share the same component, team activities filters the sessions by the teamseason selected, this is done by identifying the name of the screen, if we set it also to "Sessions" this will cause conflicts, we can do "Team Sessions" in any case.

**Comment by CritiqalPete** [comment]
@Ignacioals I need to revise the Mockup to reflect this as I am not clear on what the difference is. If you are confident you have the fix, go ahead. Otherwise, let's meet and walk though the UX and I'll update Figma as well

**Comment by Ignacioals** [comment]
@CritiqalPete  "Sessions" screen displays all sessions for all TeamSeasons a coach is part of, for a selected date. 
"Team Activities" shows only the sessions for the TeamSeason selected in the previous screen (Teams screen), we can rename this to "Team Sessions" if this solution is ok with you.
