### ISSUE TITLE
Coach can change the viewed Season from their home screen or when using a calendar to navigate

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-CoachApp#46]
The Season is an important filtering property in the data hierarchy of teams
1. Coach logs in
2. The Home Screen clearly shows the active season as an interactive element near the top
3. If the user wishes to view a different season, they can change it directly (eg. L/R Swipe to go forward or backward). The option restricts to available seasons provided by the API.
4. The view changes to reflect the selected season everywhere

Dependencies:
https://github.com/AmericaSCORESBayArea/AmericaScores-attendanceApp/issues/46

**Comment by CritiqalPete** [comment]
@Ignacioals do we need to defer this to next milestone?

**Comment by Ignacioals** [comment]
@CritiqalPete our best option for this would be to create a new endpoint to retrieve multiple seasons and also modify the current endpoint that retrieves teamseasons to filter them by a specific season, currently this endpoint orders the teamseasons by season in descending order, showing the teams from the latest season at the top, but it's not filtered by a *specific* season
