### ISSUE TITLE
[Bug] (iOS) Logo does not appear on sign-in screen

### ISSUE THREAD

**Issue by Abbybretado** [AmericaSCORESBayArea/AmericaScores-CoachApp#475]
Logo does not appear on sign-in screen

1. Open America Scores Attendance App
2. Logo does not appear on sign-in screen and appears as white space

**Expected behavior**
Logo should appear when user opens app and views sign-in screen.

**Screenshots**
If applicable, add screenshots to help explain your observation.
![IMG_0816](https://github.com/AmericaSCORESBayArea/AmericaScores-CoachApp/assets/165066898/737f2f9e-1452-4128-b991-b9d648768e7d)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 16.3
 - Browser n/a
 - App Version 20.8
- Public or Test version? Public

**Comment by CritiqalPete** [comment]
Release 2.81 fixes this. Will
Share on TestFlight for verification. 
Anyone who can test please install TestFlight and let me know what email to add to the testers group. (The one that is your Apple ID)

**Comment by CritiqalPete** [comment]
Ready for testing on v20.82 (68 on Play)
