### ISSUE TITLE
Add Coach Name to the top of their Profile Screen

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-CoachApp#484]
The screen lacks identity and is an important place for features which will allow Coaches to configure their experience.
the profile screen is accessible under the three dot menu in the upper right corner.

**Comment by Abbybretado** [comment]
<img width="372" alt="image" src="https://github.com/AmericaSCORESBayArea/AmericaScores-CoachApp/assets/165066898/65c68003-d0ff-4d15-b394-e729129f8a7c">
