### ISSUE TITLE
Remove Affiliation select from the front of the UX

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-CoachApp#509]
Presently the Affiliates we present are not active on Coach App. It doesn't need to be a choice at the beginning. The initial flow has other things that could be more valuable, like the [Coach Checklist](https://github.com/AmericaSCORESBayArea/AmericaScores-CoachApp/issues/486).

**Comment by za-zohaib** [comment]
@CritiqalPete which affiliation we need to select by default if we are going ahead without selecting any from UI ( please see image attached ) Thanks
<img width="385" alt="image" src="https://github.com/AmericaSCORESBayArea/AmericaScores-CoachApp/assets/122387654/730c964f-b520-48fc-b79a-0a68050bd636">

**Comment by CritiqalPete** [comment]
this week would be great @za-zohaib

**Comment by za-zohaib** [comment]
@CritiqalPete I mean from the three options available on Affiliation screen ASBA, IFC, OGSC which one we need to select by default if we remove this selection screen. Thanks

**Comment by za-zohaib** [comment]
As discussed we will select ASBA by Default. Thanks Pete
